# Generated by Django 4.2.17 on 2024-12-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pixeltrackerrequest',
            name='msg_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
